title: jowaka31's blog
description: > 
  일반적인 것들에 대한 <br>
  구체적인 이야기.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: /:year/:month/:day/:title/

# Navigation
navigation:
  - title: Diary
    children:
      - diary
  - title: Data
    children:
      - Machine-Learning
      - Deep-Learning
  - title: Development
    children:
      - Python
      - Web

# Author information
author:
  name: jowaka
  # bio: 
  image: ./assets/images/jowaka31.png  # Add your profile image here
  
  social:
    github: jowaka31
    # linkedin: your-linkedin-username
    email: jowaka31@gmail.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/" 